// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "AvitoTask/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// Mockuser is a mock of user interface.
type Mockuser struct {
	ctrl     *gomock.Controller
	recorder *MockuserMockRecorder
}

// MockuserMockRecorder is the mock recorder for Mockuser.
type MockuserMockRecorder struct {
	mock *Mockuser
}

// NewMockuser creates a new mock instance.
func NewMockuser(ctrl *gomock.Controller) *Mockuser {
	mock := &Mockuser{ctrl: ctrl}
	mock.recorder = &MockuserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser) EXPECT() *MockuserMockRecorder {
	return m.recorder
}

// GetUserById mocks base method.
func (m *Mockuser) GetUserById(ctx context.Context, tx pgx.Tx, userID string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, tx, userID)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockuserMockRecorder) GetUserById(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*Mockuser)(nil).GetUserById), ctx, tx, userID)
}

// GetUserCoins mocks base method.
func (m *Mockuser) GetUserCoins(ctx context.Context, tx pgx.Tx, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCoins", ctx, tx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCoins indicates an expected call of GetUserCoins.
func (mr *MockuserMockRecorder) GetUserCoins(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCoins", reflect.TypeOf((*Mockuser)(nil).GetUserCoins), ctx, tx, userID)
}

// Mockinventory is a mock of inventory interface.
type Mockinventory struct {
	ctrl     *gomock.Controller
	recorder *MockinventoryMockRecorder
}

// MockinventoryMockRecorder is the mock recorder for Mockinventory.
type MockinventoryMockRecorder struct {
	mock *Mockinventory
}

// NewMockinventory creates a new mock instance.
func NewMockinventory(ctrl *gomock.Controller) *Mockinventory {
	mock := &Mockinventory{ctrl: ctrl}
	mock.recorder = &MockinventoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockinventory) EXPECT() *MockinventoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *Mockinventory) BeginTx(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockinventoryMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*Mockinventory)(nil).BeginTx), ctx)
}

// GetInventoryItem mocks base method.
func (m *Mockinventory) GetInventoryItem(ctx context.Context, tx pgx.Tx, userID, itemType string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventoryItem", ctx, tx, userID, itemType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventoryItem indicates an expected call of GetInventoryItem.
func (mr *MockinventoryMockRecorder) GetInventoryItem(ctx, tx, userID, itemType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventoryItem", reflect.TypeOf((*Mockinventory)(nil).GetInventoryItem), ctx, tx, userID, itemType)
}

// GetUserInventory mocks base method.
func (m *Mockinventory) GetUserInventory(ctx context.Context, tx pgx.Tx, userID string) ([]models.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInventory", ctx, tx, userID)
	ret0, _ := ret[0].([]models.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInventory indicates an expected call of GetUserInventory.
func (mr *MockinventoryMockRecorder) GetUserInventory(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInventory", reflect.TypeOf((*Mockinventory)(nil).GetUserInventory), ctx, tx, userID)
}

// Mocktransaction is a mock of transaction interface.
type Mocktransaction struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionMockRecorder
}

// MocktransactionMockRecorder is the mock recorder for Mocktransaction.
type MocktransactionMockRecorder struct {
	mock *Mocktransaction
}

// NewMocktransaction creates a new mock instance.
func NewMocktransaction(ctrl *gomock.Controller) *Mocktransaction {
	mock := &Mocktransaction{ctrl: ctrl}
	mock.recorder = &MocktransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransaction) EXPECT() *MocktransactionMockRecorder {
	return m.recorder
}

// GetUserTransactions mocks base method.
func (m *Mocktransaction) GetUserTransactions(ctx context.Context, tx pgx.Tx, userID string) ([]models.TransactionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransactions", ctx, tx, userID)
	ret0, _ := ret[0].([]models.TransactionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTransactions indicates an expected call of GetUserTransactions.
func (mr *MocktransactionMockRecorder) GetUserTransactions(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransactions", reflect.TypeOf((*Mocktransaction)(nil).GetUserTransactions), ctx, tx, userID)
}
